### ISSUE TITLE
Update travis file

### ISSUE THREAD

**Issue by MartinTroll** [Olivier0393/xbmc#3]
Trying to update the .travis.yml file so the continuous integration can be trigger easily on every branch.
Travis should also be turn back on for the project.
A pull request is already start for this issue : #2

**Comment by Olivier0393** [comment]
Please add more detail to the issue so we understand the request.

**Comment by Olivier0393** [comment]
Trying to update the travis file we found that the travis limitation prevent us to use travis. Further work is needed on the travis file before reopenning an issue and a pull request.
